### ISSUE TITLE
Not working permissions issue

### ISSUE THREAD

**Issue by jasondecola** [rajkumar-rangaraj/MAWSFileExplorer#6]
Hi we have installed the Extension in Kudu but when we run it we get the following error:

You do not have permission to view this directory or page.

**Comment by facundo771** [comment]
Same problem here, I have the Owner role attached but still getting the same error ater installing and restarting the site: "You do not have permission to view this directory or page."

**Comment by dcbrown16** [comment]
Same issue here (after restarting the site).

**Comment by mohdemraan** [comment]
I'm also getting this error. Can you please look into this? I have subscription admin role but still getting permission error.

**Comment by benwhere** [comment]
Same issue , after root not found restart site and then" You do not have permission to view this directory or page."

**Comment by alanta** [comment]
I ran into the same issue and managed to work around it by cloning this repo, doing a local publish and copying the deployed files into D:\home\SiteExtensions\MAWSFileExplorer using the Kudu cmd debug console.

**Comment by rajkumar-rangaraj** [comment]
Issue is fixed. Nuget package had an issue. Please reinstall the extension.
